-- Run with a role that can create a warehouse and database.
CREATE WAREHOUSE IF NOT EXISTS STUDENT_SALES_ETL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'ETL compute for the Student Sales Data Warehouse';

CREATE DATABASE IF NOT EXISTS STUDENT_SALES_DW
    COMMENT = 'Student Sales dimensional Data Warehouse';

CREATE SCHEMA IF NOT EXISTS STUDENT_SALES_DW.CONTROL COMMENT = 'ETL audit and data-quality results';
CREATE SCHEMA IF NOT EXISTS STUDENT_SALES_DW.STAGE COMMENT = 'Transient normalized Silver staging tables';
CREATE SCHEMA IF NOT EXISTS STUDENT_SALES_DW.CORE COMMENT = 'Star Schema dimensions and facts';
CREATE SCHEMA IF NOT EXISTS STUDENT_SALES_DW.ANALYTICS COMMENT = 'Business-facing analytical views';

USE WAREHOUSE STUDENT_SALES_ETL_WH;
USE DATABASE STUDENT_SALES_DW;

CREATE OR REPLACE FILE FORMAT STAGE.SILVER_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null', '<NA>')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    ENCODING = 'UTF8';

CREATE STAGE IF NOT EXISTS STAGE.SILVER_INTERNAL_STAGE
    FILE_FORMAT = STAGE.SILVER_CSV_FORMAT
    COMMENT = 'Internal stage for normalized Silver CSV files';
