USE DATABASE STUDENT_SALES_DW;
USE SCHEMA CONTROL;

CREATE OR REPLACE TABLE ETL_BATCH_LOG (
    BATCH_RUN_ID NUMBER(38,0) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_MODE VARCHAR(50) NOT NULL,
    STARTED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    COMPLETED_AT_UTC TIMESTAMP_NTZ,
    STATUS VARCHAR(50) NOT NULL,
    SOURCE_PATH VARCHAR(2000) NOT NULL,
    MESSAGE VARCHAR(4000),
    CONSTRAINT PK_ETL_BATCH_LOG PRIMARY KEY (BATCH_RUN_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE ETL_DATASET_LOG (
    BATCH_RUN_ID NUMBER(38,0) NOT NULL,
    DATASET_NAME VARCHAR(100) NOT NULL,
    SOURCE_ROW_COUNT NUMBER(38,0) NOT NULL,
    TARGET_TABLE VARCHAR(255) NOT NULL,
    TARGET_ROW_COUNT NUMBER(38,0) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ETL_DATASET_LOG PRIMARY KEY (BATCH_RUN_ID, DATASET_NAME) NOT ENFORCED,
    CONSTRAINT FK_DATASET_BATCH FOREIGN KEY (BATCH_RUN_ID) REFERENCES ETL_BATCH_LOG (BATCH_RUN_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE DQ_RESULTS (
    CHECK_ID NUMBER(38,0) NOT NULL,
    CHECK_NAME VARCHAR(500) NOT NULL,
    CHECK_GROUP VARCHAR(100) NOT NULL,
    EXPECTED_VALUE NUMBER(38,6),
    ACTUAL_VALUE NUMBER(38,6),
    STATUS VARCHAR(20) NOT NULL,
    DETAILS VARCHAR(4000),
    CHECKED_AT_UTC TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_DQ_RESULTS PRIMARY KEY (CHECK_ID) NOT ENFORCED
);
