USE DATABASE STUDENT_SALES_DW;
USE SCHEMA STAGE;

CREATE OR REPLACE TRANSIENT TABLE STG_CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0), ZIP VARCHAR, CITY VARCHAR, SIGNUP_DATE DATE,
    GENDER VARCHAR, AGE_GROUP VARCHAR, ACQUISITION_CHANNEL VARCHAR,
    DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR, SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_GEOGRAPHY (
    ZIP VARCHAR, CITY VARCHAR, REGION VARCHAR, DISTRICT VARCHAR,
    DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR, SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_PRODUCTS (
    PRODUCT_ID NUMBER(38,0), PRODUCT_NAME VARCHAR, CATEGORY VARCHAR,
    SEGMENT VARCHAR, SIZE VARCHAR, COLOR VARCHAR, PRICE NUMBER(18,2),
    COGS NUMBER(18,2), DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_PROMOTIONS (
    PROMO_ID VARCHAR, PROMO_NAME VARCHAR, PROMO_TYPE VARCHAR,
    DISCOUNT_VALUE NUMBER(18,2), START_DATE DATE, END_DATE DATE,
    APPLICABLE_CATEGORY VARCHAR, PROMO_CHANNEL VARCHAR, STACKABLE_FLAG BOOLEAN,
    MIN_ORDER_VALUE NUMBER(18,2), DATA_QUALITY_STATUS VARCHAR,
    WARNING_CODES VARCHAR, SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0),
    BATCH_ID VARCHAR, PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_ORDERS_ENRICHED (
    ORDER_ID NUMBER(38,0), ORDER_DATE DATE, CUSTOMER_ID NUMBER(38,0),
    ZIP VARCHAR, CITY VARCHAR, REGION VARCHAR, DISTRICT VARCHAR,
    ORDER_STATUS VARCHAR, PAYMENT_METHOD VARCHAR, DEVICE_TYPE VARCHAR,
    ORDER_SOURCE VARCHAR, SALES_EMPLOYEE_ID VARCHAR, SALES_EMPLOYEE_NAME VARCHAR,
    MARITAL_STATUS VARCHAR, EDUCATION_LEVEL VARCHAR, YEARS_EXPERIENCE NUMBER(10,0),
    COMMENT VARCHAR, DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_ORDER_ITEMS (
    ORDER_ID NUMBER(38,0), PRODUCT_ID NUMBER(38,0), QUANTITY NUMBER(18,0),
    UNIT_PRICE NUMBER(18,2), DISCOUNT_AMOUNT NUMBER(18,2), PROMO_ID VARCHAR,
    PROMO_ID_2 VARCHAR, DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_PAYMENTS (
    ORDER_ID NUMBER(38,0), PAYMENT_METHOD VARCHAR, PAYMENT_VALUE NUMBER(20,2),
    INSTALLMENTS NUMBER(10,0), DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_RETURNS (
    RETURN_ID VARCHAR, ORDER_ID NUMBER(38,0), PRODUCT_ID NUMBER(38,0),
    RETURN_DATE DATE, RETURN_REASON VARCHAR, RETURN_QUANTITY NUMBER(18,0),
    REFUND_AMOUNT NUMBER(20,2), DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_REVIEWS (
    REVIEW_ID VARCHAR, ORDER_ID NUMBER(38,0), PRODUCT_ID NUMBER(38,0),
    CUSTOMER_ID NUMBER(38,0), REVIEW_DATE DATE, RATING NUMBER(2,0),
    REVIEW_TITLE VARCHAR, DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_SHIPMENTS (
    SHIPPER_ID VARCHAR, ORDER_ID NUMBER(38,0), SHIP_DATE DATE, DELIVERY_DATE DATE,
    SHIPPING_FEE NUMBER(20,2), SHIPPER_COMPANY VARCHAR, SHIPPER_VEHICLE VARCHAR,
    SHIPPER_EXPERIENCE_YEARS NUMBER(10,0), SHIPPER_RATING NUMBER(10,4),
    DELIVERY_SUCCESS_RATE NUMBER(10,4), AVERAGE_DELIVERY_TIME NUMBER(10,0),
    WORKING_SHIFT VARCHAR, JOIN_DATE DATE, SHIPPER_NAME VARCHAR,
    SHIPPER_PHONE VARCHAR, SHIPPER_GENDER VARCHAR, SHIPPER_AGE NUMBER(10,0),
    SHIPPER_MARITAL_STATUS VARCHAR, SHIPPER_EDUCATION VARCHAR, CITY VARCHAR,
    REGION VARCHAR, DISTRICT VARCHAR, DATA_QUALITY_STATUS VARCHAR,
    WARNING_CODES VARCHAR, SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0),
    BATCH_ID VARCHAR, PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_INVENTORY (
    SNAPSHOT_DATE DATE, PRODUCT_ID NUMBER(38,0), STOCK_ON_HAND NUMBER(18,0),
    UNITS_RECEIVED NUMBER(18,0), UNITS_SOLD NUMBER(18,0),
    STOCKOUT_DAYS NUMBER(18,0), DAYS_OF_SUPPLY NUMBER(18,4),
    FILL_RATE NUMBER(18,6), STOCKOUT_FLAG BOOLEAN, OVERSTOCK_FLAG BOOLEAN,
    REORDER_FLAG BOOLEAN, SELL_THROUGH_RATE NUMBER(18,6), PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR, SEGMENT VARCHAR, YEAR NUMBER(4,0), MONTH NUMBER(2,0),
    DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR, SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE STG_WEB_TRAFFIC (
    DATE DATE, SESSIONS NUMBER(18,0), UNIQUE_VISITORS NUMBER(18,0),
    PAGE_VIEWS NUMBER(18,0), BOUNCE_RATE NUMBER(18,6),
    AVG_SESSION_DURATION_SEC NUMBER(18,4), REPORTING_PERIOD VARCHAR,
    TRAFFIC_SOURCE VARCHAR, DATA_QUALITY_STATUS VARCHAR, WARNING_CODES VARCHAR,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0), BATCH_ID VARCHAR,
    PROCESSED_AT_UTC TIMESTAMP_NTZ, RECORD_HASH VARCHAR
);
