USE WAREHOUSE STUDENT_SALES_ETL_WH;
USE DATABASE STUDENT_SALES_DW;
USE SCHEMA CORE;

INSERT INTO DIM_DATE (
    DATE_KEY, FULL_DATE, DAY_OF_MONTH, DAY_NAME, DAY_OF_WEEK, WEEK_OF_YEAR,
    MONTH_NUMBER, MONTH_NAME, QUARTER_NUMBER, YEAR_NUMBER, YEAR_MONTH, IS_WEEKEND
)
WITH ALL_DATES AS (
    SELECT ORDER_DATE AS D FROM STAGE.STG_ORDERS_ENRICHED
    UNION ALL SELECT SIGNUP_DATE FROM STAGE.STG_CUSTOMERS
    UNION ALL SELECT START_DATE FROM STAGE.STG_PROMOTIONS
    UNION ALL SELECT END_DATE FROM STAGE.STG_PROMOTIONS
    UNION ALL SELECT SNAPSHOT_DATE FROM STAGE.STG_INVENTORY
    UNION ALL SELECT RETURN_DATE FROM STAGE.STG_RETURNS
    UNION ALL SELECT REVIEW_DATE FROM STAGE.STG_REVIEWS
    UNION ALL SELECT SHIP_DATE FROM STAGE.STG_SHIPMENTS
    UNION ALL SELECT DELIVERY_DATE FROM STAGE.STG_SHIPMENTS
    UNION ALL SELECT JOIN_DATE FROM STAGE.STG_SHIPMENTS
    UNION ALL SELECT DATE FROM STAGE.STG_WEB_TRAFFIC
), BOUNDS AS (
    SELECT MIN(D) AS MIN_DATE, MAX(D) AS MAX_DATE FROM ALL_DATES WHERE D IS NOT NULL
), CALENDAR_CANDIDATES AS (
    SELECT DATEADD('DAY', SEQ4(), MIN_DATE)::DATE AS FULL_DATE, MAX_DATE
    FROM BOUNDS, TABLE(GENERATOR(ROWCOUNT => 20000))
)
SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')),
    FULL_DATE,
    DAY(FULL_DATE),
    DAYNAME(FULL_DATE),
    DAYOFWEEKISO(FULL_DATE),
    WEEKISO(FULL_DATE),
    MONTH(FULL_DATE),
    MONTHNAME(FULL_DATE),
    QUARTER(FULL_DATE),
    YEAR(FULL_DATE),
    TO_CHAR(FULL_DATE, 'YYYY-MM'),
    DAYOFWEEKISO(FULL_DATE) IN (6, 7)
FROM CALENDAR_CANDIDATES
WHERE FULL_DATE <= MAX_DATE;

INSERT INTO DIM_GEOGRAPHY VALUES
(0, 'UNKNOWN', 'Unknown', 'Unknown', 'Unknown', NULL, '1900-01-01', '9999-12-31', TRUE);

INSERT INTO DIM_GEOGRAPHY (
    GEOGRAPHY_KEY, ZIP, CITY, REGION, DISTRICT, RECORD_HASH, VALID_FROM, VALID_TO, IS_CURRENT
)
SELECT ROW_NUMBER() OVER (ORDER BY ZIP), ZIP, CITY, REGION, DISTRICT, RECORD_HASH,
       '1900-01-01'::DATE, '9999-12-31'::DATE, TRUE
FROM STAGE.STG_GEOGRAPHY;

INSERT INTO DIM_CUSTOMER VALUES
(0, -1, NULL, 0, 'UNKNOWN', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL,
 '1900-01-01', '9999-12-31', TRUE);

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_KEY, CUSTOMER_ID, SIGNUP_DATE_KEY, GEOGRAPHY_KEY, ZIP, CITY, GENDER,
    AGE_GROUP, ACQUISITION_CHANNEL, RECORD_HASH, VALID_FROM, VALID_TO, IS_CURRENT
)
SELECT ROW_NUMBER() OVER (ORDER BY C.CUSTOMER_ID), C.CUSTOMER_ID,
       TO_NUMBER(TO_CHAR(C.SIGNUP_DATE, 'YYYYMMDD')), COALESCE(G.GEOGRAPHY_KEY, 0),
       C.ZIP, C.CITY, C.GENDER, C.AGE_GROUP, C.ACQUISITION_CHANNEL, C.RECORD_HASH,
       '1900-01-01'::DATE, '9999-12-31'::DATE, TRUE
FROM STAGE.STG_CUSTOMERS C
LEFT JOIN DIM_GEOGRAPHY G ON G.ZIP = C.ZIP;

INSERT INTO DIM_PRODUCT VALUES
(0, -1, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 0, 0, NULL,
 '1900-01-01', '9999-12-31', TRUE);

INSERT INTO DIM_PRODUCT (
    PRODUCT_KEY, PRODUCT_ID, PRODUCT_NAME, CATEGORY, SEGMENT, SIZE, COLOR,
    LIST_PRICE, STANDARD_COGS, RECORD_HASH, VALID_FROM, VALID_TO, IS_CURRENT
)
SELECT ROW_NUMBER() OVER (ORDER BY PRODUCT_ID), PRODUCT_ID, PRODUCT_NAME, CATEGORY,
       SEGMENT, SIZE, COLOR, PRICE, COGS, RECORD_HASH,
       '1900-01-01'::DATE, '9999-12-31'::DATE, TRUE
FROM STAGE.STG_PRODUCTS;

INSERT INTO DIM_PROMOTION VALUES
(0, 'NO_PROMO', 'No promotion', 'none', 0, NULL, NULL, 'ALL', 'all_channels', FALSE,
 0, NULL, '1900-01-01', '9999-12-31', TRUE);

INSERT INTO DIM_PROMOTION (
    PROMOTION_KEY, PROMO_ID, PROMO_NAME, PROMO_TYPE, DISCOUNT_VALUE, START_DATE_KEY,
    END_DATE_KEY, APPLICABLE_CATEGORY, PROMO_CHANNEL, STACKABLE_FLAG, MIN_ORDER_VALUE,
    RECORD_HASH, VALID_FROM, VALID_TO, IS_CURRENT
)
SELECT ROW_NUMBER() OVER (ORDER BY PROMO_ID), PROMO_ID, PROMO_NAME, PROMO_TYPE,
       DISCOUNT_VALUE, TO_NUMBER(TO_CHAR(START_DATE, 'YYYYMMDD')),
       TO_NUMBER(TO_CHAR(END_DATE, 'YYYYMMDD')), APPLICABLE_CATEGORY,
       PROMO_CHANNEL, STACKABLE_FLAG, MIN_ORDER_VALUE, RECORD_HASH,
       '1900-01-01'::DATE, '9999-12-31'::DATE, TRUE
FROM STAGE.STG_PROMOTIONS;

INSERT INTO DIM_SALES_EMPLOYEE VALUES
(0, 'UNKNOWN', 'Unknown', 'Unknown', 'Unknown', 0, '1900-01-01', '9999-12-31', TRUE);

INSERT INTO DIM_SALES_EMPLOYEE (
    SALES_EMPLOYEE_KEY, SALES_EMPLOYEE_ID, SALES_EMPLOYEE_NAME, MARITAL_STATUS,
    EDUCATION_LEVEL, YEARS_EXPERIENCE, VALID_FROM, VALID_TO, IS_CURRENT
)
WITH CURRENT_ROWS AS (
    SELECT SALES_EMPLOYEE_ID, SALES_EMPLOYEE_NAME, MARITAL_STATUS, EDUCATION_LEVEL,
           YEARS_EXPERIENCE
    FROM STAGE.STG_ORDERS_ENRICHED
    WHERE SALES_EMPLOYEE_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SALES_EMPLOYEE_ID ORDER BY ORDER_DATE DESC, ORDER_ID DESC
    ) = 1
)
SELECT ROW_NUMBER() OVER (ORDER BY SALES_EMPLOYEE_ID), SALES_EMPLOYEE_ID,
       SALES_EMPLOYEE_NAME, MARITAL_STATUS, EDUCATION_LEVEL, YEARS_EXPERIENCE,
       '1900-01-01'::DATE, '9999-12-31'::DATE, TRUE
FROM CURRENT_ROWS;

INSERT INTO DIM_SHIPPER VALUES
(0, 'UNKNOWN', 'Unknown', 'Unknown', 'Unknown', 0, 0, 0, 0, 'Unknown', NULL,
 'Unknown', 0, 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown',
 '1900-01-01', '9999-12-31', TRUE);

INSERT INTO DIM_SHIPPER (
    SHIPPER_KEY, SHIPPER_ID, SHIPPER_NAME, SHIPPER_COMPANY, SHIPPER_VEHICLE,
    SHIPPER_EXPERIENCE_YEARS, SHIPPER_RATING, DELIVERY_SUCCESS_RATE,
    AVERAGE_DELIVERY_TIME, WORKING_SHIFT, JOIN_DATE_KEY, SHIPPER_GENDER,
    SHIPPER_AGE, SHIPPER_MARITAL_STATUS, SHIPPER_EDUCATION, HOME_CITY,
    HOME_REGION, HOME_DISTRICT, VALID_FROM, VALID_TO, IS_CURRENT
)
WITH CURRENT_ROWS AS (
    SELECT *
    FROM STAGE.STG_SHIPMENTS
    WHERE SHIPPER_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SHIPPER_ID ORDER BY DELIVERY_DATE DESC, ORDER_ID DESC
    ) = 1
)
SELECT ROW_NUMBER() OVER (ORDER BY SHIPPER_ID), SHIPPER_ID, SHIPPER_NAME,
       SHIPPER_COMPANY, SHIPPER_VEHICLE, SHIPPER_EXPERIENCE_YEARS, SHIPPER_RATING,
       DELIVERY_SUCCESS_RATE, AVERAGE_DELIVERY_TIME, WORKING_SHIFT,
       TO_NUMBER(TO_CHAR(JOIN_DATE, 'YYYYMMDD')), SHIPPER_GENDER, SHIPPER_AGE,
       SHIPPER_MARITAL_STATUS, SHIPPER_EDUCATION, CITY, REGION, DISTRICT,
       '1900-01-01'::DATE, '9999-12-31'::DATE, TRUE
FROM CURRENT_ROWS;

INSERT INTO FACT_SALES (
    SALES_KEY, ORDER_ID, SOURCE_ROW_NUMBER, ORDER_DATE_KEY, CUSTOMER_KEY,
    PRODUCT_KEY, GEOGRAPHY_KEY, SALES_EMPLOYEE_KEY, PRIMARY_PROMOTION_KEY,
    SECONDARY_PROMOTION_KEY, ORDER_STATUS, PAYMENT_METHOD, DEVICE_TYPE,
    ORDER_SOURCE, QUANTITY, UNIT_PRICE, GROSS_SALES_AMOUNT, DISCOUNT_AMOUNT,
    NET_SALES_AMOUNT, COGS_AMOUNT, GROSS_PROFIT_AMOUNT, DATA_QUALITY_STATUS,
    SOURCE_RECORD_HASH, ETL_LOADED_AT_UTC
)
SELECT ROW_NUMBER() OVER (ORDER BY I.ORDER_ID, I.SOURCE_ROW_NUMBER),
       I.ORDER_ID, I.SOURCE_ROW_NUMBER, TO_NUMBER(TO_CHAR(O.ORDER_DATE, 'YYYYMMDD')),
       COALESCE(C.CUSTOMER_KEY, 0), COALESCE(P.PRODUCT_KEY, 0),
       COALESCE(G.GEOGRAPHY_KEY, 0), COALESCE(E.SALES_EMPLOYEE_KEY, 0),
       COALESCE(PR1.PROMOTION_KEY, 0), COALESCE(PR2.PROMOTION_KEY, 0),
       O.ORDER_STATUS, O.PAYMENT_METHOD, O.DEVICE_TYPE, O.ORDER_SOURCE,
       I.QUANTITY, I.UNIT_PRICE,
       ROUND(I.QUANTITY * I.UNIT_PRICE, 2),
       ROUND(I.DISCOUNT_AMOUNT, 2),
       ROUND((I.QUANTITY * I.UNIT_PRICE) - I.DISCOUNT_AMOUNT, 2),
       ROUND(I.QUANTITY * COALESCE(P.STANDARD_COGS, 0), 2),
       ROUND(((I.QUANTITY * I.UNIT_PRICE) - I.DISCOUNT_AMOUNT)
             - (I.QUANTITY * COALESCE(P.STANDARD_COGS, 0)), 2),
       I.DATA_QUALITY_STATUS, I.RECORD_HASH, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_ORDER_ITEMS I
JOIN STAGE.STG_ORDERS_ENRICHED O ON O.ORDER_ID = I.ORDER_ID
LEFT JOIN DIM_CUSTOMER C ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN DIM_PRODUCT P ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN DIM_GEOGRAPHY G ON G.ZIP = O.ZIP
LEFT JOIN DIM_SALES_EMPLOYEE E ON E.SALES_EMPLOYEE_ID = O.SALES_EMPLOYEE_ID
LEFT JOIN DIM_PROMOTION PR1 ON PR1.PROMO_ID = I.PROMO_ID
LEFT JOIN DIM_PROMOTION PR2 ON PR2.PROMO_ID = I.PROMO_ID_2;

INSERT INTO FACT_PAYMENTS (
    PAYMENT_KEY, ORDER_ID, ORDER_DATE_KEY, CUSTOMER_KEY, PAYMENT_METHOD,
    PAYMENT_VALUE, INSTALLMENTS, SOURCE_RECORD_HASH, ETL_LOADED_AT_UTC
)
SELECT ROW_NUMBER() OVER (ORDER BY P.ORDER_ID), P.ORDER_ID,
       TO_NUMBER(TO_CHAR(O.ORDER_DATE, 'YYYYMMDD')), COALESCE(C.CUSTOMER_KEY, 0),
       P.PAYMENT_METHOD, P.PAYMENT_VALUE, P.INSTALLMENTS, P.RECORD_HASH,
       CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_PAYMENTS P
JOIN STAGE.STG_ORDERS_ENRICHED O ON O.ORDER_ID = P.ORDER_ID
LEFT JOIN DIM_CUSTOMER C ON C.CUSTOMER_ID = O.CUSTOMER_ID;

INSERT INTO FACT_RETURNS (
    RETURN_KEY, RETURN_ID, ORDER_ID, PRODUCT_KEY, CUSTOMER_KEY, RETURN_DATE_KEY,
    RETURN_REASON, RETURN_QUANTITY, REFUND_AMOUNT, DATA_QUALITY_STATUS,
    SOURCE_RECORD_HASH, ETL_LOADED_AT_UTC
)
SELECT ROW_NUMBER() OVER (ORDER BY R.RETURN_ID), R.RETURN_ID, R.ORDER_ID,
       COALESCE(P.PRODUCT_KEY, 0), COALESCE(C.CUSTOMER_KEY, 0),
       TO_NUMBER(TO_CHAR(R.RETURN_DATE, 'YYYYMMDD')),
       R.RETURN_REASON, R.RETURN_QUANTITY, R.REFUND_AMOUNT, R.DATA_QUALITY_STATUS,
       R.RECORD_HASH, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_RETURNS R
LEFT JOIN DIM_PRODUCT P ON P.PRODUCT_ID = R.PRODUCT_ID
LEFT JOIN STAGE.STG_ORDERS_ENRICHED O ON O.ORDER_ID = R.ORDER_ID
LEFT JOIN DIM_CUSTOMER C ON C.CUSTOMER_ID = O.CUSTOMER_ID;

INSERT INTO FACT_REVIEWS
SELECT ROW_NUMBER() OVER (ORDER BY R.REVIEW_ID), R.REVIEW_ID, R.ORDER_ID,
       COALESCE(P.PRODUCT_KEY, 0), COALESCE(C.CUSTOMER_KEY, 0),
       TO_NUMBER(TO_CHAR(R.REVIEW_DATE, 'YYYYMMDD')), R.RATING, R.REVIEW_TITLE,
       R.DATA_QUALITY_STATUS, R.RECORD_HASH, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_REVIEWS R
LEFT JOIN DIM_PRODUCT P ON P.PRODUCT_ID = R.PRODUCT_ID
LEFT JOIN DIM_CUSTOMER C ON C.CUSTOMER_ID = R.CUSTOMER_ID;

INSERT INTO FACT_SHIPMENTS
SELECT ROW_NUMBER() OVER (ORDER BY S.ORDER_ID), S.ORDER_ID,
       COALESCE(SH.SHIPPER_KEY, 0), TO_NUMBER(TO_CHAR(S.SHIP_DATE, 'YYYYMMDD')),
       TO_NUMBER(TO_CHAR(S.DELIVERY_DATE, 'YYYYMMDD')), S.SHIPPING_FEE,
       DATEDIFF('DAY', S.SHIP_DATE, S.DELIVERY_DATE), S.DATA_QUALITY_STATUS,
       S.RECORD_HASH, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_SHIPMENTS S
LEFT JOIN DIM_SHIPPER SH ON SH.SHIPPER_ID = S.SHIPPER_ID;

INSERT INTO FACT_INVENTORY_SNAPSHOT
SELECT ROW_NUMBER() OVER (ORDER BY I.SNAPSHOT_DATE, I.PRODUCT_ID),
       TO_NUMBER(TO_CHAR(I.SNAPSHOT_DATE, 'YYYYMMDD')), COALESCE(P.PRODUCT_KEY, 0),
       I.STOCK_ON_HAND, I.UNITS_RECEIVED, I.UNITS_SOLD, I.STOCKOUT_DAYS,
       I.DAYS_OF_SUPPLY, I.FILL_RATE, I.STOCKOUT_FLAG, I.OVERSTOCK_FLAG,
       I.REORDER_FLAG, I.SELL_THROUGH_RATE, I.DATA_QUALITY_STATUS, I.RECORD_HASH,
       CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_INVENTORY I
LEFT JOIN DIM_PRODUCT P ON P.PRODUCT_ID = I.PRODUCT_ID;

INSERT INTO FACT_WEB_TRAFFIC
SELECT ROW_NUMBER() OVER (ORDER BY DATE, TRAFFIC_SOURCE),
       TO_NUMBER(TO_CHAR(DATE, 'YYYYMMDD')), TRAFFIC_SOURCE, REPORTING_PERIOD,
       SESSIONS, UNIQUE_VISITORS, PAGE_VIEWS, BOUNCE_RATE,
       AVG_SESSION_DURATION_SEC, DATA_QUALITY_STATUS, RECORD_HASH,
       CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_WEB_TRAFFIC;

INSERT INTO FACT_ORDERS (
    ORDER_KEY, ORDER_ID, ORDER_DATE_KEY, CUSTOMER_KEY, GEOGRAPHY_KEY,
    SALES_EMPLOYEE_KEY, SHIPPER_KEY, SHIP_DATE_KEY, DELIVERY_DATE_KEY,
    ORDER_STATUS, PAYMENT_METHOD, DEVICE_TYPE, ORDER_SOURCE, ORDER_COUNT,
    DELIVERED_ORDER_COUNT, RETURNED_ORDER_COUNT, ITEM_LINE_COUNT, TOTAL_QUANTITY,
    GROSS_SALES_AMOUNT, DISCOUNT_AMOUNT, NET_SALES_AMOUNT, COGS_AMOUNT,
    GROSS_PROFIT_AMOUNT, PAYMENT_VALUE, SHIPPING_FEE, REFUND_AMOUNT,
    NET_REVENUE_AFTER_RETURNS, DAYS_TO_SHIP, DAYS_TO_DELIVER, ETL_LOADED_AT_UTC
)
WITH LINE_AGG AS (
    SELECT ORDER_ID, COUNT(*) AS ITEM_LINE_COUNT, SUM(QUANTITY) AS TOTAL_QUANTITY,
           SUM(GROSS_SALES_AMOUNT) AS GROSS_SALES_AMOUNT,
           SUM(DISCOUNT_AMOUNT) AS DISCOUNT_AMOUNT,
           SUM(NET_SALES_AMOUNT) AS NET_SALES_AMOUNT,
           SUM(COGS_AMOUNT) AS COGS_AMOUNT,
           SUM(GROSS_PROFIT_AMOUNT) AS GROSS_PROFIT_AMOUNT
    FROM FACT_SALES GROUP BY ORDER_ID
), RETURN_AGG AS (
    SELECT ORDER_ID, SUM(REFUND_AMOUNT) AS REFUND_AMOUNT
    FROM FACT_RETURNS GROUP BY ORDER_ID
)
SELECT ROW_NUMBER() OVER (ORDER BY O.ORDER_ID), O.ORDER_ID,
       TO_NUMBER(TO_CHAR(O.ORDER_DATE, 'YYYYMMDD')),
       COALESCE(C.CUSTOMER_KEY, 0), COALESCE(G.GEOGRAPHY_KEY, 0),
       COALESCE(E.SALES_EMPLOYEE_KEY, 0), COALESCE(SH.SHIPPER_KEY, 0),
       FS.SHIP_DATE_KEY, FS.DELIVERY_DATE_KEY, O.ORDER_STATUS, O.PAYMENT_METHOD,
       O.DEVICE_TYPE, O.ORDER_SOURCE, 1,
       IFF(LOWER(O.ORDER_STATUS) = 'delivered', 1, 0),
       IFF(LOWER(O.ORDER_STATUS) = 'returned', 1, 0),
       COALESCE(L.ITEM_LINE_COUNT, 0), COALESCE(L.TOTAL_QUANTITY, 0),
       ROUND(COALESCE(L.GROSS_SALES_AMOUNT, 0), 2),
       ROUND(COALESCE(L.DISCOUNT_AMOUNT, 0), 2),
       ROUND(COALESCE(L.NET_SALES_AMOUNT, 0), 2),
       ROUND(COALESCE(L.COGS_AMOUNT, 0), 2),
       ROUND(COALESCE(L.GROSS_PROFIT_AMOUNT, 0), 2),
       ROUND(COALESCE(FP.PAYMENT_VALUE, 0), 2),
       ROUND(COALESCE(FS.SHIPPING_FEE, 0), 2),
       ROUND(COALESCE(R.REFUND_AMOUNT, 0), 2),
       ROUND(COALESCE(L.NET_SALES_AMOUNT, 0) - COALESCE(R.REFUND_AMOUNT, 0), 2),
       IFF(FS.SHIP_DATE_KEY IS NULL, NULL,
           DATEDIFF('DAY', O.ORDER_DATE, TO_DATE(TO_VARCHAR(FS.SHIP_DATE_KEY), 'YYYYMMDD'))),
       FS.DAYS_TO_DELIVER,
       CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM STAGE.STG_ORDERS_ENRICHED O
LEFT JOIN DIM_CUSTOMER C ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN DIM_GEOGRAPHY G ON G.ZIP = O.ZIP
LEFT JOIN DIM_SALES_EMPLOYEE E ON E.SALES_EMPLOYEE_ID = O.SALES_EMPLOYEE_ID
LEFT JOIN LINE_AGG L ON L.ORDER_ID = O.ORDER_ID
LEFT JOIN FACT_PAYMENTS FP ON FP.ORDER_ID = O.ORDER_ID
LEFT JOIN FACT_SHIPMENTS FS ON FS.ORDER_ID = O.ORDER_ID
LEFT JOIN DIM_SHIPPER SH ON SH.SHIPPER_KEY = FS.SHIPPER_KEY
LEFT JOIN RETURN_AGG R ON R.ORDER_ID = O.ORDER_ID;
