USE DATABASE STUDENT_SALES_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_SALES_DAILY AS
SELECT D.FULL_DATE AS ORDER_DATE, D.YEAR_NUMBER, D.MONTH_NUMBER,
       COUNT(DISTINCT F.ORDER_ID) AS ORDER_COUNT,
       SUM(F.QUANTITY) AS UNITS_SOLD,
       ROUND(SUM(F.GROSS_SALES_AMOUNT), 2) AS GROSS_SALES,
       ROUND(SUM(F.DISCOUNT_AMOUNT), 2) AS DISCOUNT_AMOUNT,
       ROUND(SUM(F.NET_SALES_AMOUNT), 2) AS NET_SALES,
       ROUND(SUM(F.COGS_AMOUNT), 2) AS COGS,
       ROUND(SUM(F.GROSS_PROFIT_AMOUNT), 2) AS GROSS_PROFIT
FROM CORE.FACT_SALES F
JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.ORDER_DATE_KEY
GROUP BY D.FULL_DATE, D.YEAR_NUMBER, D.MONTH_NUMBER;

CREATE OR REPLACE VIEW VW_PRODUCT_PERFORMANCE AS
WITH SALES AS (
    SELECT PRODUCT_KEY, COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT,
           SUM(QUANTITY) AS UNITS_SOLD, SUM(NET_SALES_AMOUNT) AS NET_SALES,
           SUM(GROSS_PROFIT_AMOUNT) AS GROSS_PROFIT
    FROM CORE.FACT_SALES GROUP BY PRODUCT_KEY
), REVIEWS AS (
    SELECT PRODUCT_KEY, AVG(RATING) AS AVERAGE_RATING,
           COUNT(DISTINCT REVIEW_ID) AS REVIEW_COUNT
    FROM CORE.FACT_REVIEWS GROUP BY PRODUCT_KEY
), RETURNS AS (
    SELECT PRODUCT_KEY, SUM(REFUND_AMOUNT) AS REFUND_AMOUNT
    FROM CORE.FACT_RETURNS GROUP BY PRODUCT_KEY
)
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, P.SEGMENT,
       COALESCE(S.ORDER_COUNT, 0) AS ORDER_COUNT,
       COALESCE(S.UNITS_SOLD, 0) AS UNITS_SOLD,
       ROUND(COALESCE(S.NET_SALES, 0), 2) AS NET_SALES,
       ROUND(COALESCE(S.GROSS_PROFIT, 0), 2) AS GROSS_PROFIT,
       ROUND(R.AVERAGE_RATING, 2) AS AVERAGE_RATING,
       COALESCE(R.REVIEW_COUNT, 0) AS REVIEW_COUNT,
       ROUND(COALESCE(RET.REFUND_AMOUNT, 0), 2) AS REFUND_AMOUNT
FROM CORE.DIM_PRODUCT P
LEFT JOIN SALES S ON S.PRODUCT_KEY = P.PRODUCT_KEY
LEFT JOIN REVIEWS R ON R.PRODUCT_KEY = P.PRODUCT_KEY
LEFT JOIN RETURNS RET ON RET.PRODUCT_KEY = P.PRODUCT_KEY
WHERE P.PRODUCT_KEY <> 0;

CREATE OR REPLACE VIEW VW_CUSTOMER_360 AS
SELECT C.CUSTOMER_ID, C.GENDER, C.AGE_GROUP, C.ACQUISITION_CHANNEL, C.HOME_CITY,
       COUNT(DISTINCT O.ORDER_ID) AS ORDER_COUNT,
       ROUND(COALESCE(SUM(O.NET_SALES_AMOUNT), 0), 2) AS NET_SALES,
       ROUND(COALESCE(SUM(O.REFUND_AMOUNT), 0), 2) AS REFUND_AMOUNT,
       ROUND(COALESCE(SUM(O.NET_REVENUE_AFTER_RETURNS), 0), 2) AS NET_REVENUE_AFTER_RETURNS,
       MIN(D.FULL_DATE) AS FIRST_ORDER_DATE,
       MAX(D.FULL_DATE) AS LATEST_ORDER_DATE
FROM CORE.DIM_CUSTOMER C
LEFT JOIN CORE.FACT_ORDERS O ON O.CUSTOMER_KEY = C.CUSTOMER_KEY
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = O.ORDER_DATE_KEY
WHERE C.CUSTOMER_KEY <> 0
GROUP BY C.CUSTOMER_ID, C.GENDER, C.AGE_GROUP, C.ACQUISITION_CHANNEL, C.HOME_CITY;

CREATE OR REPLACE VIEW VW_INVENTORY_LATEST AS
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, D.FULL_DATE AS SNAPSHOT_DATE,
       I.STOCK_ON_HAND, I.DAYS_OF_SUPPLY, I.FILL_RATE, I.STOCKOUT_FLAG,
       I.OVERSTOCK_FLAG, I.REORDER_FLAG, I.SELL_THROUGH_RATE
FROM CORE.FACT_INVENTORY_SNAPSHOT I
JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = I.PRODUCT_KEY
JOIN CORE.DIM_DATE D ON D.DATE_KEY = I.SNAPSHOT_DATE_KEY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY I.PRODUCT_KEY ORDER BY I.SNAPSHOT_DATE_KEY DESC
) = 1;

CREATE OR REPLACE VIEW VW_MARKETING_DAILY AS
WITH ORDERS_BY_SOURCE AS (
    SELECT ORDER_DATE_KEY, ORDER_SOURCE, COUNT(*) AS ORDER_COUNT,
           SUM(NET_SALES_AMOUNT) AS NET_SALES
    FROM CORE.FACT_ORDERS
    GROUP BY ORDER_DATE_KEY, ORDER_SOURCE
)
SELECT D.FULL_DATE, T.TRAFFIC_SOURCE, T.SESSIONS, T.UNIQUE_VISITORS,
       T.PAGE_VIEWS, T.BOUNCE_RATE, T.AVG_SESSION_DURATION_SEC,
       COALESCE(O.ORDER_COUNT, 0) AS ORDER_COUNT,
       ROUND(COALESCE(O.NET_SALES, 0), 2) AS NET_SALES,
       IFF(T.SESSIONS = 0, NULL,
           ROUND(COALESCE(O.ORDER_COUNT, 0)::FLOAT / T.SESSIONS, 6)) AS OBSERVED_ORDER_CONVERSION_RATE
FROM CORE.FACT_WEB_TRAFFIC T
JOIN CORE.DIM_DATE D ON D.DATE_KEY = T.TRAFFIC_DATE_KEY
LEFT JOIN ORDERS_BY_SOURCE O
  ON O.ORDER_DATE_KEY = T.TRAFFIC_DATE_KEY
 AND O.ORDER_SOURCE = T.TRAFFIC_SOURCE;

CREATE OR REPLACE VIEW VW_DELIVERY_PERFORMANCE AS
SELECT S.SHIPPER_COMPANY, S.HOME_REGION, COUNT(*) AS SHIPMENT_COUNT,
       ROUND(AVG(F.DAYS_TO_DELIVER), 2) AS AVERAGE_DAYS_TO_DELIVER,
       ROUND(AVG(F.SHIPPING_FEE), 2) AS AVERAGE_SHIPPING_FEE,
       ROUND(AVG(S.SHIPPER_RATING), 2) AS AVERAGE_SHIPPER_RATING,
       ROUND(AVG(S.DELIVERY_SUCCESS_RATE), 2) AS AVERAGE_DELIVERY_SUCCESS_RATE
FROM CORE.FACT_SHIPMENTS F
JOIN CORE.DIM_SHIPPER S ON S.SHIPPER_KEY = F.SHIPPER_KEY
GROUP BY S.SHIPPER_COMPANY, S.HOME_REGION;

CREATE OR REPLACE VIEW VW_PROMOTION_PERFORMANCE AS
SELECT P.PROMO_ID, P.PROMO_NAME, P.PROMO_TYPE, P.PROMO_CHANNEL,
       COUNT(DISTINCT B.SALES_KEY) AS SALES_LINE_COUNT,
       ROUND(SUM(F.QUANTITY * B.ALLOCATION_WEIGHT), 2) AS ATTRIBUTED_UNITS,
       SUM(F.GROSS_SALES_AMOUNT * B.ALLOCATION_WEIGHT) AS ATTRIBUTED_GROSS_SALES,
       SUM(F.DISCOUNT_AMOUNT * B.ALLOCATION_WEIGHT) AS ATTRIBUTED_DISCOUNT,
       SUM(F.NET_SALES_AMOUNT * B.ALLOCATION_WEIGHT) AS ATTRIBUTED_NET_SALES,
       SUM(F.GROSS_PROFIT_AMOUNT * B.ALLOCATION_WEIGHT) AS ATTRIBUTED_GROSS_PROFIT
FROM CORE.BRIDGE_SALES_PROMOTION B
JOIN CORE.FACT_SALES F ON F.SALES_KEY = B.SALES_KEY
JOIN CORE.DIM_PROMOTION P ON P.PROMOTION_KEY = B.PROMOTION_KEY
GROUP BY P.PROMO_ID, P.PROMO_NAME, P.PROMO_TYPE, P.PROMO_CHANNEL;
