USE WAREHOUSE STUDENT_SALES_ETL_WH;
USE DATABASE STUDENT_SALES_DW;
USE SCHEMA CONTROL;

DELETE FROM DQ_RESULTS WHERE BATCH_RUN_ID = $BATCH_RUN_ID;

INSERT INTO DQ_RESULTS (
    BATCH_RUN_ID, CHECK_ID, CHECK_NAME, CHECK_GROUP,
    EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS
)
WITH RAW_CHECKS AS (
    SELECT 1 AS CHECK_ID, 'Dimension business-key uniqueness' AS CHECK_NAME,
           'grain' AS CHECK_GROUP, 0::NUMBER(38,6) AS EXPECTED_VALUE,
           (
             SELECT COALESCE(SUM(DUPLICATES), 0) FROM (
               SELECT COUNT(*) - 1 AS DUPLICATES FROM CORE.DIM_GEOGRAPHY WHERE GEOGRAPHY_KEY <> 0 GROUP BY ZIP HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.DIM_CUSTOMER WHERE CUSTOMER_KEY <> 0 GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.DIM_PRODUCT WHERE PRODUCT_KEY <> 0 GROUP BY PRODUCT_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.DIM_PROMOTION WHERE PROMOTION_KEY <> 0 GROUP BY PROMO_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.DIM_SALES_EMPLOYEE WHERE SALES_EMPLOYEE_KEY <> 0 GROUP BY SALES_EMPLOYEE_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.DIM_SHIPPER WHERE SHIPPER_KEY <> 0 GROUP BY SHIPPER_ID HAVING COUNT(*) > 1
             )
           )::NUMBER(38,6) AS ACTUAL_VALUE,
           0::NUMBER(38,6) AS TOLERANCE,
           'Natural keys in all six business dimensions must be unique' AS DETAILS

    UNION ALL
    SELECT 2, 'Fact grain uniqueness', 'grain', 0,
           (
             SELECT COALESCE(SUM(DUPLICATES), 0) FROM (
               SELECT COUNT(*) - 1 AS DUPLICATES FROM CORE.FACT_SALES GROUP BY ORDER_ID, SOURCE_ROW_NUMBER HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_ORDERS GROUP BY ORDER_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_PAYMENTS GROUP BY ORDER_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_RETURNS GROUP BY RETURN_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_REVIEWS GROUP BY REVIEW_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_SHIPMENTS GROUP BY ORDER_ID HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_INVENTORY_SNAPSHOT GROUP BY SNAPSHOT_DATE_KEY, PRODUCT_KEY HAVING COUNT(*) > 1
               UNION ALL SELECT COUNT(*) - 1 FROM CORE.FACT_WEB_TRAFFIC GROUP BY TRAFFIC_DATE_KEY, TRAFFIC_SOURCE HAVING COUNT(*) > 1
             )
           ), 0,
           'All eight declared fact grains must be unique'

    UNION ALL
    SELECT 3, 'Promotion bridge sequence uniqueness', 'grain', 0,
           (SELECT COUNT(*) FROM (
              SELECT SALES_KEY, PROMOTION_SEQUENCE FROM CORE.BRIDGE_SALES_PROMOTION
              GROUP BY SALES_KEY, PROMOTION_SEQUENCE HAVING COUNT(*) > 1
           )), 0,
           'Each sales line can use a promotion sequence at most once'

    UNION ALL
    SELECT 4, 'Sales required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.ORDER_DATE_KEY = 0 OR F.CUSTOMER_KEY = 0 OR F.PRODUCT_KEY = 0
                    OR F.GEOGRAPHY_KEY = 0 OR F.SALES_EMPLOYEE_KEY = 0
                    OR D.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR P.PRODUCT_KEY IS NULL
                    OR G.GEOGRAPHY_KEY IS NULL OR E.SALES_EMPLOYEE_KEY IS NULL),
           0, 'Every sales line must resolve to five conformed dimensions'
    FROM CORE.FACT_SALES F
    LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.ORDER_DATE_KEY
    LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
    LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY
    LEFT JOIN CORE.DIM_GEOGRAPHY G ON G.GEOGRAPHY_KEY = F.GEOGRAPHY_KEY
    LEFT JOIN CORE.DIM_SALES_EMPLOYEE E ON E.SALES_EMPLOYEE_KEY = F.SALES_EMPLOYEE_KEY

    UNION ALL
    SELECT 5, 'Payment required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.ORDER_DATE_KEY = 0 OR F.CUSTOMER_KEY = 0 OR D.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL),
           0, 'Every payment must resolve to order date and customer'
    FROM CORE.FACT_PAYMENTS F
    LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.ORDER_DATE_KEY
    LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY

    UNION ALL
    SELECT 6, 'Return required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.ORDER_DATE_KEY = 0 OR F.RETURN_DATE_KEY = 0 OR F.PRODUCT_KEY = 0 OR F.CUSTOMER_KEY = 0
                    OR OD.DATE_KEY IS NULL OR RD.DATE_KEY IS NULL OR P.PRODUCT_KEY IS NULL OR C.CUSTOMER_KEY IS NULL),
           0, 'Every return must resolve to order date, return date, product and customer'
    FROM CORE.FACT_RETURNS F
    LEFT JOIN CORE.DIM_DATE OD ON OD.DATE_KEY = F.ORDER_DATE_KEY
    LEFT JOIN CORE.DIM_DATE RD ON RD.DATE_KEY = F.RETURN_DATE_KEY
    LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY
    LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY

    UNION ALL
    SELECT 7, 'Review required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.ORDER_DATE_KEY = 0 OR F.REVIEW_DATE_KEY = 0 OR F.PRODUCT_KEY = 0 OR F.CUSTOMER_KEY = 0
                    OR OD.DATE_KEY IS NULL OR RD.DATE_KEY IS NULL OR P.PRODUCT_KEY IS NULL OR C.CUSTOMER_KEY IS NULL),
           0, 'Every review must resolve to order date, review date, product and customer'
    FROM CORE.FACT_REVIEWS F
    LEFT JOIN CORE.DIM_DATE OD ON OD.DATE_KEY = F.ORDER_DATE_KEY
    LEFT JOIN CORE.DIM_DATE RD ON RD.DATE_KEY = F.REVIEW_DATE_KEY
    LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY
    LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY

    UNION ALL
    SELECT 8, 'Shipment required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.ORDER_DATE_KEY = 0 OR F.SHIP_DATE_KEY = 0 OR F.DELIVERY_DATE_KEY = 0
                    OR F.CUSTOMER_KEY = 0 OR F.GEOGRAPHY_KEY = 0 OR F.SHIPPER_KEY = 0
                    OR OD.DATE_KEY IS NULL OR SD.DATE_KEY IS NULL OR DD.DATE_KEY IS NULL
                    OR C.CUSTOMER_KEY IS NULL OR G.GEOGRAPHY_KEY IS NULL OR S.SHIPPER_KEY IS NULL),
           0, 'Every shipment must resolve to dates, customer, geography and shipper'
    FROM CORE.FACT_SHIPMENTS F
    LEFT JOIN CORE.DIM_DATE OD ON OD.DATE_KEY = F.ORDER_DATE_KEY
    LEFT JOIN CORE.DIM_DATE SD ON SD.DATE_KEY = F.SHIP_DATE_KEY
    LEFT JOIN CORE.DIM_DATE DD ON DD.DATE_KEY = F.DELIVERY_DATE_KEY
    LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
    LEFT JOIN CORE.DIM_GEOGRAPHY G ON G.GEOGRAPHY_KEY = F.GEOGRAPHY_KEY
    LEFT JOIN CORE.DIM_SHIPPER S ON S.SHIPPER_KEY = F.SHIPPER_KEY

    UNION ALL
    SELECT 9, 'Inventory required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.SNAPSHOT_DATE_KEY = 0 OR F.PRODUCT_KEY = 0 OR D.DATE_KEY IS NULL OR P.PRODUCT_KEY IS NULL),
           0, 'Every inventory snapshot must resolve to date and product'
    FROM CORE.FACT_INVENTORY_SNAPSHOT F
    LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.SNAPSHOT_DATE_KEY
    LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY

    UNION ALL
    SELECT 10, 'Web traffic required date key', 'referential_integrity', 0,
           COUNT_IF(F.TRAFFIC_DATE_KEY = 0 OR D.DATE_KEY IS NULL),
           0, 'Every traffic row must resolve to date'
    FROM CORE.FACT_WEB_TRAFFIC F
    LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.TRAFFIC_DATE_KEY

    UNION ALL
    SELECT 11, 'Order required dimension keys', 'referential_integrity', 0,
           COUNT_IF(F.ORDER_DATE_KEY = 0 OR F.CUSTOMER_KEY = 0 OR F.GEOGRAPHY_KEY = 0
                    OR F.SALES_EMPLOYEE_KEY = 0 OR OD.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL
                    OR G.GEOGRAPHY_KEY IS NULL OR E.SALES_EMPLOYEE_KEY IS NULL
                    OR (F.SHIP_DATE_KEY IS NOT NULL AND (F.SHIPPER_KEY = 0 OR S.SHIPPER_KEY IS NULL OR SD.DATE_KEY IS NULL))
                    OR (F.DELIVERY_DATE_KEY IS NOT NULL AND DD.DATE_KEY IS NULL)),
           0, 'Required order dimensions and populated shipment roles must resolve'
    FROM CORE.FACT_ORDERS F
    LEFT JOIN CORE.DIM_DATE OD ON OD.DATE_KEY = F.ORDER_DATE_KEY
    LEFT JOIN CORE.DIM_DATE SD ON SD.DATE_KEY = F.SHIP_DATE_KEY
    LEFT JOIN CORE.DIM_DATE DD ON DD.DATE_KEY = F.DELIVERY_DATE_KEY
    LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
    LEFT JOIN CORE.DIM_GEOGRAPHY G ON G.GEOGRAPHY_KEY = F.GEOGRAPHY_KEY
    LEFT JOIN CORE.DIM_SALES_EMPLOYEE E ON E.SALES_EMPLOYEE_KEY = F.SALES_EMPLOYEE_KEY
    LEFT JOIN CORE.DIM_SHIPPER S ON S.SHIPPER_KEY = F.SHIPPER_KEY

    UNION ALL
    SELECT 12, 'Promotion bridge foreign keys', 'referential_integrity', 0,
           COUNT_IF(F.SALES_KEY IS NULL OR P.PROMOTION_KEY IS NULL),
           0, 'Every bridge row must resolve to sales and promotion'
    FROM CORE.BRIDGE_SALES_PROMOTION B
    LEFT JOIN CORE.FACT_SALES F ON F.SALES_KEY = B.SALES_KEY
    LEFT JOIN CORE.DIM_PROMOTION P ON P.PROMOTION_KEY = B.PROMOTION_KEY

    UNION ALL
    SELECT 13, 'Promotion bridge coverage', 'bridge', 0,
           (SELECT COUNT(*) FROM (
              SELECT F.SALES_KEY FROM CORE.FACT_SALES F
              LEFT JOIN CORE.BRIDGE_SALES_PROMOTION B ON B.SALES_KEY = F.SALES_KEY
              GROUP BY F.SALES_KEY HAVING COUNT(B.SALES_KEY) = 0
           )), 0, 'Every sales line must have a promotion or NO_PROMO bridge row'

    UNION ALL
    SELECT 14, 'Promotion allocation weights', 'bridge', 0,
           (SELECT COUNT(*) FROM (
              SELECT SALES_KEY FROM CORE.BRIDGE_SALES_PROMOTION GROUP BY SALES_KEY
              HAVING ABS(SUM(ALLOCATION_WEIGHT) - 1) > 0.000001
           )), 0, 'Allocation weights per sales line must sum to 1'

    UNION ALL
    SELECT 15, 'Promotion bridge row count', 'bridge',
           (SELECT COUNT(*) FROM CORE.FACT_SALES) + (SELECT COUNT_IF(PROMO_ID_2 IS NOT NULL) FROM STAGE.STG_ORDER_ITEMS),
           (SELECT COUNT(*) FROM CORE.BRIDGE_SALES_PROMOTION),
           0,
           'One bridge row per sales line plus one for each secondary promotion'

    UNION ALL SELECT 16, 'Sales row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_ORDER_ITEMS), (SELECT COUNT(*) FROM CORE.FACT_SALES), 0, 'Silver order-item rows must equal sales fact rows'
    UNION ALL SELECT 17, 'Order row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_ORDERS_ENRICHED), (SELECT COUNT(*) FROM CORE.FACT_ORDERS), 0, 'Silver order rows must equal order fact rows'
    UNION ALL SELECT 18, 'Payment row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_PAYMENTS), (SELECT COUNT(*) FROM CORE.FACT_PAYMENTS), 0, 'Silver payment rows must equal payment fact rows'
    UNION ALL SELECT 19, 'Return row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_RETURNS), (SELECT COUNT(*) FROM CORE.FACT_RETURNS), 0, 'Silver return rows must equal return fact rows'
    UNION ALL SELECT 20, 'Review row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_REVIEWS), (SELECT COUNT(*) FROM CORE.FACT_REVIEWS), 0, 'Silver review rows must equal review fact rows'
    UNION ALL SELECT 21, 'Shipment row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_SHIPMENTS), (SELECT COUNT(*) FROM CORE.FACT_SHIPMENTS), 0, 'Silver shipment rows must equal shipment fact rows'
    UNION ALL SELECT 22, 'Inventory row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_INVENTORY), (SELECT COUNT(*) FROM CORE.FACT_INVENTORY_SNAPSHOT), 0, 'Silver inventory rows must equal inventory fact rows'
    UNION ALL SELECT 23, 'Web traffic row count', 'completeness', (SELECT COUNT(*) FROM STAGE.STG_WEB_TRAFFIC), (SELECT COUNT(*) FROM CORE.FACT_WEB_TRAFFIC), 0, 'Silver traffic rows must equal traffic fact rows'

    UNION ALL SELECT 24, 'Gross sales reconciliation', 'financial', ROUND((SELECT SUM(QUANTITY * UNIT_PRICE) FROM STAGE.STG_ORDER_ITEMS), 2), ROUND((SELECT SUM(GROSS_SALES_AMOUNT) FROM CORE.FACT_SALES), 2), 0.01, 'Gross sales must reconcile to Silver'
    UNION ALL SELECT 25, 'Discount reconciliation', 'financial', ROUND((SELECT SUM(DISCOUNT_AMOUNT) FROM STAGE.STG_ORDER_ITEMS), 2), ROUND((SELECT SUM(DISCOUNT_AMOUNT) FROM CORE.FACT_SALES), 2), 0.01, 'Discount amount must reconcile to Silver'
    UNION ALL SELECT 26, 'Net sales reconciliation', 'financial', ROUND((SELECT SUM(QUANTITY * UNIT_PRICE - DISCOUNT_AMOUNT) FROM STAGE.STG_ORDER_ITEMS), 2), ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_SALES), 2), 0.01, 'Net sales must reconcile to Silver'
    UNION ALL SELECT 27, 'Payment reconciliation', 'financial', ROUND((SELECT SUM(PAYMENT_VALUE) FROM STAGE.STG_PAYMENTS), 2), ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_PAYMENTS), 2), 0.01, 'Payment amount must reconcile to Silver'
    UNION ALL SELECT 28, 'Refund reconciliation', 'financial', ROUND((SELECT SUM(REFUND_AMOUNT) FROM STAGE.STG_RETURNS), 2), ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_RETURNS), 2), 0.01, 'Refund amount must reconcile to Silver'
    UNION ALL SELECT 29, 'Shipping-fee reconciliation', 'financial', ROUND((SELECT SUM(SHIPPING_FEE) FROM STAGE.STG_SHIPMENTS), 2), ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_SHIPMENTS), 2), 0.01, 'Shipping fees must reconcile to Silver'

    UNION ALL SELECT 30, 'Order-to-sales net consistency', 'cross_layer_consistency', ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_SALES), 2), ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_ORDERS), 2), 0.01, 'Order fact net sales must equal sales fact net sales'
    UNION ALL SELECT 31, 'Order-to-payment consistency', 'cross_layer_consistency', ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_PAYMENTS), 2), ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_ORDERS), 2), 0.01, 'Order fact payment must equal payment facts'
    UNION ALL SELECT 32, 'Order-to-return consistency', 'cross_layer_consistency', ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_RETURNS), 2), ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_ORDERS), 2), 0.01, 'Order fact refund must equal return facts'
    UNION ALL SELECT 33, 'Order-to-shipment consistency', 'cross_layer_consistency', ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_SHIPMENTS), 2), ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_ORDERS), 2), 0.01, 'Order fact shipping fee must equal shipment facts'

    UNION ALL
    SELECT 34, 'Business-domain rules', 'business_rules', 0,
           (SELECT COUNT_IF(QUANTITY <= 0 OR UNIT_PRICE < 0 OR DISCOUNT_AMOUNT < 0 OR DISCOUNT_AMOUNT > QUANTITY * UNIT_PRICE) FROM STAGE.STG_ORDER_ITEMS)
         + (SELECT COUNT_IF(PAYMENT_VALUE < 0 OR INSTALLMENTS <= 0) FROM STAGE.STG_PAYMENTS)
         + (SELECT COUNT_IF(RETURN_QUANTITY <= 0 OR REFUND_AMOUNT < 0) FROM STAGE.STG_RETURNS)
         + (SELECT COUNT_IF(RATING < 1 OR RATING > 5) FROM STAGE.STG_REVIEWS)
         + (SELECT COUNT_IF(SHIPPING_FEE < 0 OR DELIVERY_DATE < SHIP_DATE) FROM STAGE.STG_SHIPMENTS)
         + (SELECT COUNT_IF(END_DATE < START_DATE OR DISCOUNT_VALUE < 0 OR MIN_ORDER_VALUE < 0) FROM STAGE.STG_PROMOTIONS)
         + (SELECT COUNT_IF(SESSIONS < 0 OR UNIQUE_VISITORS < 0 OR PAGE_VIEWS < 0 OR BOUNCE_RATE < 0 OR BOUNCE_RATE > 1) FROM STAGE.STG_WEB_TRAFFIC),
           0, 'Numeric domains and event-date order must be valid'

    UNION ALL
    SELECT 35, 'Silver warning rows retained', 'source_quality', NULL,
           (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_PRODUCTS)
         + (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_SHIPMENTS)
         + (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_RETURNS)
         + (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_INVENTORY),
           NULL, 'Source warnings remain available in staging and relevant facts'
), CHECKS AS (
    SELECT CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE,
           CASE
             WHEN CHECK_ID = 35 THEN 'INFO'
             WHEN ABS(COALESCE(ACTUAL_VALUE, 0) - COALESCE(EXPECTED_VALUE, 0)) <= TOLERANCE THEN 'PASS'
             ELSE 'FAIL'
           END AS STATUS,
           DETAILS
    FROM RAW_CHECKS
)
SELECT $BATCH_RUN_ID, CHECK_ID, CHECK_NAME, CHECK_GROUP,
       EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS
FROM CHECKS;
