USE DATABASE STUDENT_SALES_DW;
USE SCHEMA CONTROL;

TRUNCATE TABLE DQ_RESULTS;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 1, 'Sales fact row count', 'row_count',
       (SELECT COUNT(*) FROM STAGE.STG_ORDER_ITEMS),
       (SELECT COUNT(*) FROM CORE.FACT_SALES),
       IFF((SELECT COUNT(*) FROM STAGE.STG_ORDER_ITEMS) = (SELECT COUNT(*) FROM CORE.FACT_SALES), 'PASS', 'FAIL'),
       'One FACT_SALES row is expected for each Silver order item row';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 2, 'Order fact row count', 'row_count',
       (SELECT COUNT(*) FROM STAGE.STG_ORDERS_ENRICHED),
       (SELECT COUNT(*) FROM CORE.FACT_ORDERS),
       IFF((SELECT COUNT(*) FROM STAGE.STG_ORDERS_ENRICHED) = (SELECT COUNT(*) FROM CORE.FACT_ORDERS), 'PASS', 'FAIL'),
       'One FACT_ORDERS row is expected for each Silver order row';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 3, 'All canonical datasets synchronized', 'completeness', 0,
       (SELECT COUNT(*) FROM ETL_DATASET_LOG WHERE STATUS <> 'PASS' OR SOURCE_ROW_COUNT <> TARGET_ROW_COUNT),
       IFF((SELECT COUNT(*) FROM ETL_DATASET_LOG WHERE STATUS <> 'PASS' OR SOURCE_ROW_COUNT <> TARGET_ROW_COUNT) = 0, 'PASS', 'FAIL'),
       'All 12 canonical Silver datasets must match their Gold targets';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 4, 'Net sales reconciliation', 'reconciliation',
       ROUND((SELECT SUM((QUANTITY * UNIT_PRICE) - DISCOUNT_AMOUNT) FROM STAGE.STG_ORDER_ITEMS), 2),
       ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_SALES), 2),
       IFF(ABS(
           ROUND((SELECT SUM((QUANTITY * UNIT_PRICE) - DISCOUNT_AMOUNT) FROM STAGE.STG_ORDER_ITEMS), 2)
           - ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_SALES), 2)
       ) <= 0.01, 'PASS', 'FAIL'),
       'Gold net sales must reconcile to Silver quantity times unit price less discount';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 5, 'Payment value reconciliation', 'reconciliation',
       ROUND((SELECT SUM(PAYMENT_VALUE) FROM STAGE.STG_PAYMENTS), 2),
       ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_PAYMENTS), 2),
       IFF(ABS(ROUND((SELECT SUM(PAYMENT_VALUE) FROM STAGE.STG_PAYMENTS), 2)
               - ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_PAYMENTS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Payment value must reconcile between Silver and Gold';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 6, 'Refund amount reconciliation', 'reconciliation',
       ROUND((SELECT SUM(REFUND_AMOUNT) FROM STAGE.STG_RETURNS), 2),
       ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_RETURNS), 2),
       IFF(ABS(ROUND((SELECT SUM(REFUND_AMOUNT) FROM STAGE.STG_RETURNS), 2)
               - ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_RETURNS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Refund amount must reconcile between Silver and Gold';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 7, 'Shipping fee reconciliation', 'reconciliation',
       ROUND((SELECT SUM(SHIPPING_FEE) FROM STAGE.STG_SHIPMENTS), 2),
       ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_SHIPMENTS), 2),
       IFF(ABS(ROUND((SELECT SUM(SHIPPING_FEE) FROM STAGE.STG_SHIPMENTS), 2)
               - ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_SHIPMENTS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Shipping fee must reconcile between Silver and Gold';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 8, 'Sales required dimension keys', 'referential_integrity', 0,
       COUNT_IF(D.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR P.PRODUCT_KEY IS NULL
                OR G.GEOGRAPHY_KEY IS NULL OR E.SALES_EMPLOYEE_KEY IS NULL
                OR PR1.PROMOTION_KEY IS NULL OR PR2.PROMOTION_KEY IS NULL),
       IFF(COUNT_IF(D.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR P.PRODUCT_KEY IS NULL
                    OR G.GEOGRAPHY_KEY IS NULL OR E.SALES_EMPLOYEE_KEY IS NULL
                    OR PR1.PROMOTION_KEY IS NULL OR PR2.PROMOTION_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Every sales row must resolve to required dimensions'
FROM CORE.FACT_SALES S
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = S.ORDER_DATE_KEY
LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = S.CUSTOMER_KEY
LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = S.PRODUCT_KEY
LEFT JOIN CORE.DIM_GEOGRAPHY G ON G.GEOGRAPHY_KEY = S.GEOGRAPHY_KEY
LEFT JOIN CORE.DIM_SALES_EMPLOYEE E ON E.SALES_EMPLOYEE_KEY = S.SALES_EMPLOYEE_KEY
LEFT JOIN CORE.DIM_PROMOTION PR1 ON PR1.PROMOTION_KEY = S.PRIMARY_PROMOTION_KEY
LEFT JOIN CORE.DIM_PROMOTION PR2 ON PR2.PROMOTION_KEY = S.SECONDARY_PROMOTION_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 9, 'Sales grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT ORDER_ID || '|' || SOURCE_ROW_NUMBER),
       IFF(COUNT(*) = COUNT(DISTINCT ORDER_ID || '|' || SOURCE_ROW_NUMBER), 'PASS', 'FAIL'),
       'Declared grain: one source order-item row'
FROM CORE.FACT_SALES;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 10, 'Order grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT ORDER_ID),
       IFF(COUNT(*) = COUNT(DISTINCT ORDER_ID), 'PASS', 'FAIL'),
       'Declared grain: one row per order'
FROM CORE.FACT_ORDERS;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 11, 'Payment grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT ORDER_ID),
       IFF(COUNT(*) = COUNT(DISTINCT ORDER_ID), 'PASS', 'FAIL'),
       'Declared grain: one payment per order in the current source'
FROM CORE.FACT_PAYMENTS;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 12, 'Return grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT RETURN_ID),
       IFF(COUNT(*) = COUNT(DISTINCT RETURN_ID), 'PASS', 'FAIL'),
       'Declared grain: one row per return_id'
FROM CORE.FACT_RETURNS;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 13, 'Review grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT REVIEW_ID),
       IFF(COUNT(*) = COUNT(DISTINCT REVIEW_ID), 'PASS', 'FAIL'),
       'Declared grain: one row per review_id'
FROM CORE.FACT_REVIEWS;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 14, 'Shipment grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT ORDER_ID),
       IFF(COUNT(*) = COUNT(DISTINCT ORDER_ID), 'PASS', 'FAIL'),
       'Declared grain: one shipment per order'
FROM CORE.FACT_SHIPMENTS;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 15, 'Inventory grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT SNAPSHOT_DATE_KEY || '|' || PRODUCT_KEY),
       IFF(COUNT(*) = COUNT(DISTINCT SNAPSHOT_DATE_KEY || '|' || PRODUCT_KEY), 'PASS', 'FAIL'),
       'Declared grain: one product per snapshot date'
FROM CORE.FACT_INVENTORY_SNAPSHOT;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 16, 'Web traffic grain uniqueness', 'uniqueness', 0,
       COUNT(*) - COUNT(DISTINCT TRAFFIC_DATE_KEY || '|' || TRAFFIC_SOURCE),
       IFF(COUNT(*) = COUNT(DISTINCT TRAFFIC_DATE_KEY || '|' || TRAFFIC_SOURCE), 'PASS', 'FAIL'),
       'Declared grain: one traffic source per date'
FROM CORE.FACT_WEB_TRAFFIC;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 17, 'Return required dimension keys', 'referential_integrity', 0,
       COUNT_IF(P.PRODUCT_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR D.DATE_KEY IS NULL),
       IFF(COUNT_IF(P.PRODUCT_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR D.DATE_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Returns must resolve to product, customer and return date'
FROM CORE.FACT_RETURNS F
LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY
LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.RETURN_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 18, 'Review required dimension keys', 'referential_integrity', 0,
       COUNT_IF(P.PRODUCT_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR D.DATE_KEY IS NULL),
       IFF(COUNT_IF(P.PRODUCT_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR D.DATE_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Reviews must resolve to product, customer and review date'
FROM CORE.FACT_REVIEWS F
LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY
LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.REVIEW_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 19, 'Shipment required dimension keys', 'referential_integrity', 0,
       COUNT_IF(S.SHIPPER_KEY IS NULL OR SD.DATE_KEY IS NULL OR DD.DATE_KEY IS NULL),
       IFF(COUNT_IF(S.SHIPPER_KEY IS NULL OR SD.DATE_KEY IS NULL OR DD.DATE_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Shipments must resolve to shipper, ship date and delivery date'
FROM CORE.FACT_SHIPMENTS F
LEFT JOIN CORE.DIM_SHIPPER S ON S.SHIPPER_KEY = F.SHIPPER_KEY
LEFT JOIN CORE.DIM_DATE SD ON SD.DATE_KEY = F.SHIP_DATE_KEY
LEFT JOIN CORE.DIM_DATE DD ON DD.DATE_KEY = F.DELIVERY_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 20, 'Inventory required dimension keys', 'referential_integrity', 0,
       COUNT_IF(P.PRODUCT_KEY IS NULL OR D.DATE_KEY IS NULL),
       IFF(COUNT_IF(P.PRODUCT_KEY IS NULL OR D.DATE_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Inventory snapshots must resolve to product and date'
FROM CORE.FACT_INVENTORY_SNAPSHOT F
LEFT JOIN CORE.DIM_PRODUCT P ON P.PRODUCT_KEY = F.PRODUCT_KEY
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.SNAPSHOT_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 21, 'Order-level net sales rollup', 'cross_fact_consistency',
       ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_SALES), 2),
       ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_ORDERS), 2),
       IFF(ABS(ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_SALES), 2)
               - ROUND((SELECT SUM(NET_SALES_AMOUNT) FROM CORE.FACT_ORDERS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Order fact net sales must equal line-level sales';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 22, 'Order-level payment rollup', 'cross_fact_consistency',
       ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_PAYMENTS), 2),
       ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_ORDERS), 2),
       IFF(ABS(ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_PAYMENTS), 2)
               - ROUND((SELECT SUM(PAYMENT_VALUE) FROM CORE.FACT_ORDERS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Order fact payment value must equal payment facts';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 23, 'Order-level refund rollup', 'cross_fact_consistency',
       ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_RETURNS), 2),
       ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_ORDERS), 2),
       IFF(ABS(ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_RETURNS), 2)
               - ROUND((SELECT SUM(REFUND_AMOUNT) FROM CORE.FACT_ORDERS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Order fact refund amount must equal return facts';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 24, 'Order-level shipping fee rollup', 'cross_fact_consistency',
       ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_SHIPMENTS), 2),
       ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_ORDERS), 2),
       IFF(ABS(ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_SHIPMENTS), 2)
               - ROUND((SELECT SUM(SHIPPING_FEE) FROM CORE.FACT_ORDERS), 2)) <= 0.01, 'PASS', 'FAIL'),
       'Order fact shipping fee must equal shipment facts';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 25, 'Silver warning rows retained', 'source_quality', NULL,
       (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_PRODUCTS)
       + (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_SHIPMENTS)
       + (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_RETURNS)
       + (SELECT COUNT_IF(DATA_QUALITY_STATUS = 'warning') FROM STAGE.STG_INVENTORY),
       'INFO', 'Warnings are retained and not silently discarded';

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 26, 'Order fact required dimension keys', 'referential_integrity', 0,
       COUNT_IF(OD.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR G.GEOGRAPHY_KEY IS NULL
                OR E.SALES_EMPLOYEE_KEY IS NULL OR S.SHIPPER_KEY IS NULL
                OR (F.SHIP_DATE_KEY IS NOT NULL AND SD.DATE_KEY IS NULL)
                OR (F.DELIVERY_DATE_KEY IS NOT NULL AND DD.DATE_KEY IS NULL)),
       IFF(COUNT_IF(OD.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL OR G.GEOGRAPHY_KEY IS NULL
                    OR E.SALES_EMPLOYEE_KEY IS NULL OR S.SHIPPER_KEY IS NULL
                    OR (F.SHIP_DATE_KEY IS NOT NULL AND SD.DATE_KEY IS NULL)
                    OR (F.DELIVERY_DATE_KEY IS NOT NULL AND DD.DATE_KEY IS NULL)) = 0, 'PASS', 'FAIL'),
       'Every order must resolve to required dimensions and any populated shipment dates'
FROM CORE.FACT_ORDERS F
LEFT JOIN CORE.DIM_DATE OD ON OD.DATE_KEY = F.ORDER_DATE_KEY
LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY
LEFT JOIN CORE.DIM_GEOGRAPHY G ON G.GEOGRAPHY_KEY = F.GEOGRAPHY_KEY
LEFT JOIN CORE.DIM_SALES_EMPLOYEE E ON E.SALES_EMPLOYEE_KEY = F.SALES_EMPLOYEE_KEY
LEFT JOIN CORE.DIM_SHIPPER S ON S.SHIPPER_KEY = F.SHIPPER_KEY
LEFT JOIN CORE.DIM_DATE SD ON SD.DATE_KEY = F.SHIP_DATE_KEY
LEFT JOIN CORE.DIM_DATE DD ON DD.DATE_KEY = F.DELIVERY_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 27, 'Web traffic required date key', 'referential_integrity', 0,
       COUNT_IF(D.DATE_KEY IS NULL), IFF(COUNT_IF(D.DATE_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Every traffic row must resolve to DIM_DATE'
FROM CORE.FACT_WEB_TRAFFIC F
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.TRAFFIC_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 28, 'Customer dimension relationships', 'referential_integrity', 0,
       COUNT_IF(G.GEOGRAPHY_KEY IS NULL OR (C.SIGNUP_DATE_KEY IS NOT NULL AND D.DATE_KEY IS NULL)),
       IFF(COUNT_IF(G.GEOGRAPHY_KEY IS NULL OR (C.SIGNUP_DATE_KEY IS NOT NULL AND D.DATE_KEY IS NULL)) = 0, 'PASS', 'FAIL'),
       'Every customer must resolve to geography and any populated signup date'
FROM CORE.DIM_CUSTOMER C
LEFT JOIN CORE.DIM_GEOGRAPHY G ON G.GEOGRAPHY_KEY = C.GEOGRAPHY_KEY
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = C.SIGNUP_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 29, 'Promotion dimension date relationships', 'referential_integrity', 0,
       COUNT_IF((P.START_DATE_KEY IS NOT NULL AND SD.DATE_KEY IS NULL)
                OR (P.END_DATE_KEY IS NOT NULL AND ED.DATE_KEY IS NULL)),
       IFF(COUNT_IF((P.START_DATE_KEY IS NOT NULL AND SD.DATE_KEY IS NULL)
                    OR (P.END_DATE_KEY IS NOT NULL AND ED.DATE_KEY IS NULL)) = 0, 'PASS', 'FAIL'),
       'Promotion start and end dates must resolve to DIM_DATE'
FROM CORE.DIM_PROMOTION P
LEFT JOIN CORE.DIM_DATE SD ON SD.DATE_KEY = P.START_DATE_KEY
LEFT JOIN CORE.DIM_DATE ED ON ED.DATE_KEY = P.END_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 30, 'Shipper dimension join-date relationship', 'referential_integrity', 0,
       COUNT_IF(S.JOIN_DATE_KEY IS NOT NULL AND D.DATE_KEY IS NULL),
       IFF(COUNT_IF(S.JOIN_DATE_KEY IS NOT NULL AND D.DATE_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Every populated shipper join date must resolve to DIM_DATE'
FROM CORE.DIM_SHIPPER S
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = S.JOIN_DATE_KEY;

INSERT INTO DQ_RESULTS (CHECK_ID, CHECK_NAME, CHECK_GROUP, EXPECTED_VALUE, ACTUAL_VALUE, STATUS, DETAILS)
SELECT 31, 'Payment required dimension keys', 'referential_integrity', 0,
       COUNT_IF(D.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL),
       IFF(COUNT_IF(D.DATE_KEY IS NULL OR C.CUSTOMER_KEY IS NULL) = 0, 'PASS', 'FAIL'),
       'Every payment must resolve to order date and customer dimensions'
FROM CORE.FACT_PAYMENTS F
LEFT JOIN CORE.DIM_DATE D ON D.DATE_KEY = F.ORDER_DATE_KEY
LEFT JOIN CORE.DIM_CUSTOMER C ON C.CUSTOMER_KEY = F.CUSTOMER_KEY;
