-- Snowflake Star Schema for STUDENT_SALES_DW.CORE.
-- Grain and relationships are declared as metadata constraints and enforced
-- by data_warehouse/sql/05_quality_checks.sql after every full-refresh load.

USE DATABASE STUDENT_SALES_DW;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER(8,0) NOT NULL,
    FULL_DATE DATE NOT NULL,
    DAY_OF_MONTH NUMBER(2,0) NOT NULL,
    DAY_NAME VARCHAR(10) NOT NULL,
    DAY_OF_WEEK NUMBER(1,0) NOT NULL,
    WEEK_OF_YEAR NUMBER(2,0) NOT NULL,
    MONTH_NUMBER NUMBER(2,0) NOT NULL,
    MONTH_NAME VARCHAR(10) NOT NULL,
    QUARTER_NUMBER NUMBER(1,0) NOT NULL,
    YEAR_NUMBER NUMBER(4,0) NOT NULL,
    YEAR_MONTH VARCHAR(7) NOT NULL,
    IS_WEEKEND BOOLEAN NOT NULL,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_DATE_FULL_DATE UNIQUE (FULL_DATE) NOT ENFORCED
);

CREATE OR REPLACE TABLE DIM_GEOGRAPHY (
    GEOGRAPHY_KEY NUMBER(38,0) NOT NULL,
    ZIP VARCHAR(32) NOT NULL,
    CITY VARCHAR(255),
    REGION VARCHAR(255),
    DISTRICT VARCHAR(255),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DIM_GEOGRAPHY PRIMARY KEY (GEOGRAPHY_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_GEOGRAPHY_ZIP UNIQUE (ZIP) NOT ENFORCED
);

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    HOME_ZIP VARCHAR(32),
    HOME_CITY VARCHAR(255),
    SIGNUP_DATE DATE,
    GENDER VARCHAR(50),
    AGE_GROUP VARCHAR(50),
    ACQUISITION_CHANNEL VARCHAR(100),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_CUSTOMER_ID UNIQUE (CUSTOMER_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY NUMBER(38,0) NOT NULL,
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    PRODUCT_NAME VARCHAR(500),
    CATEGORY VARCHAR(255),
    SEGMENT VARCHAR(255),
    SIZE VARCHAR(100),
    COLOR VARCHAR(100),
    LIST_PRICE NUMBER(18,6),
    STANDARD_COGS NUMBER(18,6),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (PRODUCT_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_PRODUCT_ID UNIQUE (PRODUCT_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE DIM_PROMOTION (
    PROMOTION_KEY NUMBER(38,0) NOT NULL,
    PROMO_ID VARCHAR(100) NOT NULL,
    PROMO_NAME VARCHAR(500),
    PROMO_TYPE VARCHAR(100),
    DISCOUNT_VALUE NUMBER(18,2),
    START_DATE DATE,
    END_DATE DATE,
    APPLICABLE_CATEGORY VARCHAR(255),
    PROMO_CHANNEL VARCHAR(100),
    STACKABLE_FLAG BOOLEAN,
    MIN_ORDER_VALUE NUMBER(18,2),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DIM_PROMOTION PRIMARY KEY (PROMOTION_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_PROMOTION_ID UNIQUE (PROMO_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE DIM_SALES_EMPLOYEE (
    SALES_EMPLOYEE_KEY NUMBER(38,0) NOT NULL,
    SALES_EMPLOYEE_ID VARCHAR(100) NOT NULL,
    SALES_EMPLOYEE_NAME VARCHAR(500),
    MARITAL_STATUS VARCHAR(100),
    EDUCATION_LEVEL VARCHAR(255),
    YEARS_EXPERIENCE NUMBER(10,0),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DIM_SALES_EMPLOYEE PRIMARY KEY (SALES_EMPLOYEE_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_SALES_EMPLOYEE_ID UNIQUE (SALES_EMPLOYEE_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE DIM_SHIPPER (
    SHIPPER_KEY NUMBER(38,0) NOT NULL,
    SHIPPER_ID VARCHAR(100) NOT NULL,
    SHIPPER_NAME VARCHAR(500),
    SHIPPER_PHONE VARCHAR(100),
    SHIPPER_COMPANY VARCHAR(500),
    SHIPPER_VEHICLE VARCHAR(255),
    SHIPPER_EXPERIENCE_YEARS NUMBER(10,0),
    SHIPPER_RATING NUMBER(10,4),
    DELIVERY_SUCCESS_RATE NUMBER(10,4),
    AVERAGE_DELIVERY_TIME NUMBER(10,0),
    WORKING_SHIFT VARCHAR(100),
    JOIN_DATE DATE,
    SHIPPER_GENDER VARCHAR(50),
    SHIPPER_AGE NUMBER(10,0),
    SHIPPER_MARITAL_STATUS VARCHAR(100),
    SHIPPER_EDUCATION VARCHAR(255),
    HOME_CITY VARCHAR(255),
    HOME_REGION VARCHAR(255),
    HOME_DISTRICT VARCHAR(255),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DIM_SHIPPER PRIMARY KEY (SHIPPER_KEY) NOT ENFORCED,
    CONSTRAINT UQ_DIM_SHIPPER_ID UNIQUE (SHIPPER_ID) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY NUMBER(38,0) NOT NULL,
    ORDER_ID NUMBER(38,0) NOT NULL,
    SOURCE_ROW_NUMBER NUMBER(38,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    PRODUCT_KEY NUMBER(38,0) NOT NULL,
    GEOGRAPHY_KEY NUMBER(38,0) NOT NULL,
    SALES_EMPLOYEE_KEY NUMBER(38,0) NOT NULL,
    ORDER_STATUS VARCHAR(100),
    PAYMENT_METHOD VARCHAR(100),
    DEVICE_TYPE VARCHAR(100),
    ORDER_SOURCE VARCHAR(100),
    QUANTITY NUMBER(18,0) NOT NULL,
    UNIT_PRICE NUMBER(18,2) NOT NULL,
    GROSS_SALES_AMOUNT NUMBER(20,2) NOT NULL,
    DISCOUNT_AMOUNT NUMBER(20,2) NOT NULL,
    NET_SALES_AMOUNT NUMBER(20,2) NOT NULL,
    COGS_AMOUNT NUMBER(20,2) NOT NULL,
    GROSS_PROFIT_AMOUNT NUMBER(20,2) NOT NULL,
    DATA_QUALITY_STATUS VARCHAR(50),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_SALES PRIMARY KEY (SALES_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_SALES_GRAIN UNIQUE (ORDER_ID, SOURCE_ROW_NUMBER) NOT ENFORCED,
    CONSTRAINT FK_SALES_ORDER_DATE FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER (CUSTOMER_KEY) NOT ENFORCED,
    CONSTRAINT FK_SALES_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT (PRODUCT_KEY) NOT ENFORCED,
    CONSTRAINT FK_SALES_GEOGRAPHY FOREIGN KEY (GEOGRAPHY_KEY) REFERENCES DIM_GEOGRAPHY (GEOGRAPHY_KEY) NOT ENFORCED,
    CONSTRAINT FK_SALES_EMPLOYEE FOREIGN KEY (SALES_EMPLOYEE_KEY) REFERENCES DIM_SALES_EMPLOYEE (SALES_EMPLOYEE_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE BRIDGE_SALES_PROMOTION (
    SALES_KEY NUMBER(38,0) NOT NULL,
    PROMOTION_KEY NUMBER(38,0) NOT NULL,
    PROMOTION_SEQUENCE NUMBER(1,0) NOT NULL,
    ALLOCATION_WEIGHT NUMBER(18,6) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(100),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_BRIDGE_SALES_PROMOTION PRIMARY KEY (SALES_KEY, PROMOTION_KEY) NOT ENFORCED,
    CONSTRAINT UQ_BRIDGE_SALES_PROMO_SEQUENCE UNIQUE (SALES_KEY, PROMOTION_SEQUENCE) NOT ENFORCED,
    CONSTRAINT FK_BRIDGE_SALES FOREIGN KEY (SALES_KEY) REFERENCES FACT_SALES (SALES_KEY) NOT ENFORCED,
    CONSTRAINT FK_BRIDGE_PROMOTION FOREIGN KEY (PROMOTION_KEY) REFERENCES DIM_PROMOTION (PROMOTION_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_PAYMENTS (
    PAYMENT_KEY NUMBER(38,0) NOT NULL,
    ORDER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    PAYMENT_METHOD VARCHAR(100),
    PAYMENT_VALUE NUMBER(20,2) NOT NULL,
    INSTALLMENTS NUMBER(10,0),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_PAYMENTS PRIMARY KEY (PAYMENT_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_PAYMENTS_GRAIN UNIQUE (ORDER_ID) NOT ENFORCED,
    CONSTRAINT FK_PAYMENTS_ORDER_DATE FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_PAYMENTS_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER (CUSTOMER_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_RETURNS (
    RETURN_KEY NUMBER(38,0) NOT NULL,
    RETURN_ID VARCHAR(100) NOT NULL,
    ORDER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    RETURN_DATE_KEY NUMBER(8,0) NOT NULL,
    PRODUCT_KEY NUMBER(38,0) NOT NULL,
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    RETURN_REASON VARCHAR(500),
    RETURN_QUANTITY NUMBER(18,0) NOT NULL,
    REFUND_AMOUNT NUMBER(20,2) NOT NULL,
    DATA_QUALITY_STATUS VARCHAR(50),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_RETURNS PRIMARY KEY (RETURN_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_RETURNS_GRAIN UNIQUE (RETURN_ID) NOT ENFORCED,
    CONSTRAINT FK_RETURNS_ORDER_DATE FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_RETURNS_DATE FOREIGN KEY (RETURN_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_RETURNS_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT (PRODUCT_KEY) NOT ENFORCED,
    CONSTRAINT FK_RETURNS_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER (CUSTOMER_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_REVIEWS (
    REVIEW_KEY NUMBER(38,0) NOT NULL,
    REVIEW_ID VARCHAR(100) NOT NULL,
    ORDER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    REVIEW_DATE_KEY NUMBER(8,0) NOT NULL,
    PRODUCT_KEY NUMBER(38,0) NOT NULL,
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    RATING NUMBER(2,0) NOT NULL,
    REVIEW_TITLE VARCHAR(1000),
    DATA_QUALITY_STATUS VARCHAR(50),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_REVIEWS PRIMARY KEY (REVIEW_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_REVIEWS_GRAIN UNIQUE (REVIEW_ID) NOT ENFORCED,
    CONSTRAINT FK_REVIEWS_ORDER_DATE FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_REVIEWS_DATE FOREIGN KEY (REVIEW_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_REVIEWS_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT (PRODUCT_KEY) NOT ENFORCED,
    CONSTRAINT FK_REVIEWS_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER (CUSTOMER_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_SHIPMENTS (
    SHIPMENT_KEY NUMBER(38,0) NOT NULL,
    ORDER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    SHIP_DATE_KEY NUMBER(8,0) NOT NULL,
    DELIVERY_DATE_KEY NUMBER(8,0) NOT NULL,
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    GEOGRAPHY_KEY NUMBER(38,0) NOT NULL,
    SHIPPER_KEY NUMBER(38,0) NOT NULL,
    SHIPPING_FEE NUMBER(20,2) NOT NULL,
    DAYS_TO_SHIP NUMBER(10,0),
    DAYS_TO_DELIVER NUMBER(10,0),
    DATA_QUALITY_STATUS VARCHAR(50),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_SHIPMENTS PRIMARY KEY (SHIPMENT_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_SHIPMENTS_GRAIN UNIQUE (ORDER_ID) NOT ENFORCED,
    CONSTRAINT FK_SHIPMENTS_ORDER_DATE FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_SHIPMENTS_SHIP_DATE FOREIGN KEY (SHIP_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_SHIPMENTS_DELIVERY_DATE FOREIGN KEY (DELIVERY_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_SHIPMENTS_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER (CUSTOMER_KEY) NOT ENFORCED,
    CONSTRAINT FK_SHIPMENTS_GEOGRAPHY FOREIGN KEY (GEOGRAPHY_KEY) REFERENCES DIM_GEOGRAPHY (GEOGRAPHY_KEY) NOT ENFORCED,
    CONSTRAINT FK_SHIPMENTS_SHIPPER FOREIGN KEY (SHIPPER_KEY) REFERENCES DIM_SHIPPER (SHIPPER_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_INVENTORY_SNAPSHOT (
    INVENTORY_KEY NUMBER(38,0) NOT NULL,
    SNAPSHOT_DATE_KEY NUMBER(8,0) NOT NULL,
    PRODUCT_KEY NUMBER(38,0) NOT NULL,
    STOCK_ON_HAND NUMBER(18,0) NOT NULL,
    UNITS_RECEIVED NUMBER(18,0) NOT NULL,
    UNITS_SOLD NUMBER(18,0) NOT NULL,
    STOCKOUT_DAYS NUMBER(18,0) NOT NULL,
    DAYS_OF_SUPPLY NUMBER(18,4) NOT NULL,
    FILL_RATE NUMBER(18,6) NOT NULL,
    STOCKOUT_FLAG BOOLEAN NOT NULL,
    OVERSTOCK_FLAG BOOLEAN NOT NULL,
    REORDER_FLAG BOOLEAN NOT NULL,
    SELL_THROUGH_RATE NUMBER(18,6) NOT NULL,
    DATA_QUALITY_STATUS VARCHAR(50),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_INVENTORY PRIMARY KEY (INVENTORY_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_INVENTORY_GRAIN UNIQUE (SNAPSHOT_DATE_KEY, PRODUCT_KEY) NOT ENFORCED,
    CONSTRAINT FK_INVENTORY_DATE FOREIGN KEY (SNAPSHOT_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT (PRODUCT_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_WEB_TRAFFIC (
    TRAFFIC_KEY NUMBER(38,0) NOT NULL,
    TRAFFIC_DATE_KEY NUMBER(8,0) NOT NULL,
    TRAFFIC_SOURCE VARCHAR(100) NOT NULL,
    REPORTING_PERIOD VARCHAR(100),
    SESSIONS NUMBER(18,0) NOT NULL,
    UNIQUE_VISITORS NUMBER(18,0) NOT NULL,
    PAGE_VIEWS NUMBER(18,0) NOT NULL,
    BOUNCE_RATE NUMBER(18,6) NOT NULL,
    AVG_SESSION_DURATION_SEC NUMBER(18,4) NOT NULL,
    DATA_QUALITY_STATUS VARCHAR(50),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_WEB_TRAFFIC PRIMARY KEY (TRAFFIC_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_WEB_TRAFFIC_GRAIN UNIQUE (TRAFFIC_DATE_KEY, TRAFFIC_SOURCE) NOT ENFORCED,
    CONSTRAINT FK_TRAFFIC_DATE FOREIGN KEY (TRAFFIC_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED
);

CREATE OR REPLACE TABLE FACT_ORDERS (
    ORDER_KEY NUMBER(38,0) NOT NULL,
    ORDER_ID NUMBER(38,0) NOT NULL,
    ORDER_DATE_KEY NUMBER(8,0) NOT NULL,
    CUSTOMER_KEY NUMBER(38,0) NOT NULL,
    GEOGRAPHY_KEY NUMBER(38,0) NOT NULL,
    SALES_EMPLOYEE_KEY NUMBER(38,0) NOT NULL,
    SHIPPER_KEY NUMBER(38,0) NOT NULL,
    SHIP_DATE_KEY NUMBER(8,0),
    DELIVERY_DATE_KEY NUMBER(8,0),
    ORDER_STATUS VARCHAR(100),
    PAYMENT_METHOD VARCHAR(100),
    DEVICE_TYPE VARCHAR(100),
    ORDER_SOURCE VARCHAR(100),
    ORDER_COUNT NUMBER(1,0) NOT NULL,
    DELIVERED_ORDER_COUNT NUMBER(1,0) NOT NULL,
    RETURNED_ORDER_COUNT NUMBER(1,0) NOT NULL,
    ITEM_LINE_COUNT NUMBER(18,0) NOT NULL,
    TOTAL_QUANTITY NUMBER(18,0) NOT NULL,
    GROSS_SALES_AMOUNT NUMBER(20,2) NOT NULL,
    DISCOUNT_AMOUNT NUMBER(20,2) NOT NULL,
    NET_SALES_AMOUNT NUMBER(20,2) NOT NULL,
    COGS_AMOUNT NUMBER(20,2) NOT NULL,
    GROSS_PROFIT_AMOUNT NUMBER(20,2) NOT NULL,
    PAYMENT_VALUE NUMBER(20,2) NOT NULL,
    SHIPPING_FEE NUMBER(20,2) NOT NULL,
    REFUND_AMOUNT NUMBER(20,2) NOT NULL,
    NET_REVENUE_AFTER_RETURNS NUMBER(20,2) NOT NULL,
    DAYS_TO_SHIP NUMBER(10,0),
    DAYS_TO_DELIVER NUMBER(10,0),
    SOURCE_BATCH_ID VARCHAR(100),
    SOURCE_RECORD_HASH VARCHAR(128),
    ETL_LOADED_AT_UTC TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_FACT_ORDERS PRIMARY KEY (ORDER_KEY) NOT ENFORCED,
    CONSTRAINT UQ_FACT_ORDERS_GRAIN UNIQUE (ORDER_ID) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_ORDER_DATE FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER (CUSTOMER_KEY) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_GEOGRAPHY FOREIGN KEY (GEOGRAPHY_KEY) REFERENCES DIM_GEOGRAPHY (GEOGRAPHY_KEY) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_EMPLOYEE FOREIGN KEY (SALES_EMPLOYEE_KEY) REFERENCES DIM_SALES_EMPLOYEE (SALES_EMPLOYEE_KEY) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_SHIPPER FOREIGN KEY (SHIPPER_KEY) REFERENCES DIM_SHIPPER (SHIPPER_KEY) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_SHIP_DATE FOREIGN KEY (SHIP_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED,
    CONSTRAINT FK_ORDERS_DELIVERY_DATE FOREIGN KEY (DELIVERY_DATE_KEY) REFERENCES DIM_DATE (DATE_KEY) NOT ENFORCED
);
